name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Run Tests
        run: go test ./...

      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run Security Check
        uses: securego/gosec@master
        with:
          args: ./...

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Minikube
        uses: medyagh/setup-minikube@latest

      - name: Docker Build
        run: |
          eval $(minikube -p minikube docker-env)
          docker build -t github-api .

      - name: Deploy to Minikube
        run: kubectl apply -f k8s/deployment.yaml