apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-api
  template:
    metadata:
      labels:
        app: github-api
    spec:
      containers:
      - name: github-api
        image: github-api
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: github-api-service
spec:
  type: NodePort
  selector:
    app: github-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
