name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Run tests
        run: go test ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Security
        uses: securego/gosec@v2
        with:
          args: ./...

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Build Docker Image
        run: |
          eval $(minikube docker-env)
          docker build -t github-pr-api .

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/deployment.yaml
